apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ecom2micro-minimal
type: Opaque
stringData:
  # PostgreSQL Credentials
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres123"
  
  # JWT Configuration
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
  JWT_ISSUER: "ecom2micro"
  JWT_AUDIENCE: "ecom2micro-api"
  
  # Kafka SASL (optional for minimal)
  KAFKA_SASL_USERNAME: ""
  KAFKA_SASL_PASSWORD: ""
